// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZF6wHAkx20BKu5lu11bA8ZhGxt0GRw_Y',
    appId: '1:168128553328:web:2dc2ce5645230a6540efb5',
    messagingSenderId: '168128553328',
    projectId: 'walltutorial-9f790',
    authDomain: 'walltutorial-9f790.firebaseapp.com',
    storageBucket: 'walltutorial-9f790.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIGTEE9RyF6VWtL1YqUVVlJNM8VHZXImY',
    appId: '1:168128553328:android:7a766ebe0c0aeb3140efb5',
    messagingSenderId: '168128553328',
    projectId: 'walltutorial-9f790',
    storageBucket: 'walltutorial-9f790.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfoNzbFJBbNDfeI-439S2Rb6aZ2Py5U0o',
    appId: '1:168128553328:ios:90a9dc469ab5ec6d40efb5',
    messagingSenderId: '168128553328',
    projectId: 'walltutorial-9f790',
    storageBucket: 'walltutorial-9f790.appspot.com',
    iosBundleId: 'com.example.demo9',
  );
}
